import type {
  Booking,
  CastingCall,
  Creator,
  PressMention,
  UploadItem,
} from "./types";

// Seed data is illustrative only. In production this is sourced from the
// authenticated app API which queries the platform's Postgres + content services.

export const creators: Creator[] = [
  {
    id: "01HZ8K3M0001",
    handle: "amelia.vance",
    displayName: "Amelia Vance",
    pronouns: "she / her",
    tagline: "Editorial · Movement · Latex",
    city: "New York",
    borough: "TriBeCa",
    agencyOfRecord: "Mother / NY",
    tier: 4,
    joinedYear: 2023,
    measurements: {
      height: "5'10\"",
      bust: "32B",
      waist: "24",
      hips: "35",
      shoe: "9",
      hair: "Auburn",
      eyes: "Hazel",
    },
    disciplines: ["Editorial", "Runway", "Movement", "Latex"],
    languages: ["English", "French", "Italian"],
    unionMemberships: ["SAG-AFTRA"],
    portraitUrl:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=1600&q=80",
    bio: "Trained at SUNY Purchase. Movement-led performer with a portfolio that spans private commissions for European fashion houses and editorial work for independent publications.",
    representedBy: "Mother / NY · Folio Talent (Paris)",
    reels: 14,
    followers: "184k",
    bookings: 62,
    rating: 4.96,
    rateCardCents: 480000,
  },
  {
    id: "01HZ8K3M0002",
    handle: "noor.calloway",
    displayName: "Noor Calloway",
    pronouns: "they / them",
    tagline: "Conceptual · Fine Art · Performance",
    city: "Brooklyn",
    borough: "Bushwick",
    agencyOfRecord: "Independent",
    tier: 4,
    joinedYear: 2022,
    measurements: {
      height: "6'1\"",
      shoe: "12",
      hair: "Shaved",
      eyes: "Brown",
    },
    disciplines: ["Conceptual", "Fine Art", "Performance", "Voice"],
    languages: ["English", "Arabic"],
    portraitUrl:
      "https://images.unsplash.com/photo-1542327897-d73f4005b533?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1600&q=80",
    bio: "Multi-disciplinary performer working at the seam of dance, fashion, and conceptual film. Recent commissions for The Shed and Performa Biennial.",
    reels: 22,
    followers: "92k",
    bookings: 41,
    rating: 4.92,
    rateCardCents: 320000,
  },
  {
    id: "01HZ8K3M0003",
    handle: "ines.delacroix",
    displayName: "Inès Delacroix",
    pronouns: "she / her",
    tagline: "Couture · Fragrance · Print",
    city: "New York",
    borough: "West Village",
    agencyOfRecord: "Folio Talent",
    tier: 3,
    joinedYear: 2024,
    measurements: {
      height: "5'9\"",
      bust: "32A",
      waist: "23",
      hips: "34",
      shoe: "8.5",
      hair: "Platinum",
      eyes: "Blue",
    },
    disciplines: ["Couture", "Print", "Fragrance"],
    languages: ["English", "French"],
    portraitUrl:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1600&q=80",
    bio: "Paris-born, New York-based. Walked F/W for three of the four major weeks. Print and fragrance specialist with a discreet client roster.",
    reels: 8,
    followers: "211k",
    bookings: 34,
    rating: 4.88,
    rateCardCents: 540000,
  },
  {
    id: "01HZ8K3M0004",
    handle: "marcus.holt",
    displayName: "Marcus Holt",
    pronouns: "he / him",
    tagline: "Tailoring · Watches · Cinema",
    city: "New York",
    borough: "Lower East Side",
    agencyOfRecord: "Wilhelmina Men",
    tier: 3,
    joinedYear: 2021,
    measurements: {
      height: "6'2\"",
      shoe: "11",
      hair: "Black",
      eyes: "Brown",
    },
    disciplines: ["Tailoring", "Watch", "Cinematic"],
    languages: ["English", "Spanish"],
    unionMemberships: ["SAG-AFTRA"],
    portraitUrl:
      "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1485217988980-11786ced9454?auto=format&fit=crop&w=1600&q=80",
    bio: "Architect-turned-performer. Specializes in stillness, hands-only work, and editorial film. Repeated bookings with Italian and Swiss heritage houses.",
    reels: 11,
    followers: "67k",
    bookings: 53,
    rating: 4.94,
    rateCardCents: 380000,
  },
  {
    id: "01HZ8K3M0005",
    handle: "saoirse.bell",
    displayName: "Saoirse Bell",
    pronouns: "she / her",
    tagline: "Fine Lingerie · Lifestyle · Boudoir",
    city: "New York",
    borough: "SoHo",
    agencyOfRecord: "Independent",
    tier: 4,
    joinedYear: 2022,
    measurements: {
      height: "5'7\"",
      bust: "34C",
      waist: "25",
      hips: "36",
      shoe: "8",
      hair: "Chestnut",
      eyes: "Green",
    },
    disciplines: ["Lingerie", "Lifestyle", "Boudoir", "Voice"],
    languages: ["English"],
    portraitUrl:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1600&q=80",
    bio: "Discreet client list across European intimates houses and private collectors. All work delivered through the platform's view-once and invite-key surfaces.",
    reels: 19,
    followers: "326k",
    bookings: 78,
    rating: 4.97,
    rateCardCents: 620000,
  },
  {
    id: "01HZ8K3M0006",
    handle: "kenji.aoki",
    displayName: "Kenji Aoki",
    pronouns: "he / him",
    tagline: "Avant-Garde · Choreographed Stillness",
    city: "New York",
    borough: "Chelsea",
    agencyOfRecord: "Independent",
    tier: 3,
    joinedYear: 2024,
    measurements: {
      height: "5'11\"",
      shoe: "10",
      hair: "Black",
      eyes: "Brown",
    },
    disciplines: ["Avant-Garde", "Movement", "Print"],
    languages: ["English", "Japanese"],
    portraitUrl:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1600&q=80",
    bio: "Trained at Juilliard. Bridges contemporary dance and fashion. Frequently commissioned for opening looks and closing tableaux.",
    reels: 7,
    followers: "44k",
    bookings: 29,
    rating: 4.89,
    rateCardCents: 290000,
  },
  {
    id: "01HZ8K3M0007",
    handle: "vera.osei",
    displayName: "Vera Osei",
    pronouns: "she / her",
    tagline: "Beauty · Skin · Hair",
    city: "Brooklyn",
    borough: "Fort Greene",
    agencyOfRecord: "Mother / NY",
    tier: 4,
    joinedYear: 2021,
    measurements: {
      height: "5'8\"",
      hair: "Natural 4B",
      eyes: "Brown",
    },
    disciplines: ["Beauty", "Skin", "Hair", "Lifestyle"],
    languages: ["English", "Twi", "French"],
    portraitUrl:
      "https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1495567720989-cebdbdd97913?auto=format&fit=crop&w=1600&q=80",
    bio: "Skin and hair specialist. Recurring face for two heritage cosmetic houses. Selective on private commissions; available for global travel.",
    reels: 16,
    followers: "418k",
    bookings: 95,
    rating: 4.98,
    rateCardCents: 720000,
  },
  {
    id: "01HZ8K3M0008",
    handle: "rhys.alderman",
    displayName: "Rhys Alderman",
    pronouns: "he / him",
    tagline: "Print · Cinematic · Voice-of-Brand",
    city: "New York",
    borough: "Greenpoint",
    agencyOfRecord: "Wilhelmina Men",
    tier: 3,
    joinedYear: 2023,
    measurements: {
      height: "6'0\"",
      shoe: "10.5",
      hair: "Sandy Blonde",
      eyes: "Blue",
    },
    disciplines: ["Print", "Cinematic", "Voice"],
    languages: ["English"],
    unionMemberships: ["SAG-AFTRA"],
    portraitUrl:
      "https://images.unsplash.com/photo-1500336624523-d727130c3328?auto=format&fit=crop&w=900&q=80",
    coverUrl:
      "https://images.unsplash.com/photo-1493514789931-586cb221d7a7?auto=format&fit=crop&w=1600&q=80",
    bio: "Quiet face of two American heritage brands. Specializes in slow editorial film and recurring brand voice work.",
    reels: 9,
    followers: "73k",
    bookings: 47,
    rating: 4.91,
    rateCardCents: 360000,
  },
];

export const castingCalls: CastingCall[] = [
  {
    id: "CC-2026-0411",
    slug: "maison-vermeer-fw26",
    title: "Maison Vermeer · F/W 26 Campaign",
    productionHouse: "Maison Vermeer",
    productionType: "Campaign",
    location: "Manhattan & Catskills",
    shootWindow: "May 18 — May 22, 2026",
    ratePerDayCents: 850000,
    ratePerDayLabel: "$8,500 / day",
    closesOn: "2026-05-09",
    postedOn: "2026-04-27",
    status: "Open",
    union: "Either",
    exclusivity: "Worldwide, fashion category, 18 months",
    usage: "Print · Digital · OOH · Editorial film",
    brief:
      "A meditation on light, texture, and the architecture of restraint. Looking for distinctive faces, range 22–34, capable of stillness with an inner pulse. Editorial film component requires comfort with movement direction and minimal dialog.",
    requirements: [
      "Tier 3 or above platform verification",
      "Comfort with bare-skin tailoring",
      "Movement reel within last 12 months",
      "Available for full shoot window",
    ],
    submissionsCount: 412,
    spots: 6,
    posterUrl:
      "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=1600&q=80",
    director: "Anouk Renaud",
    stylist: "Jordan Lim",
    photographer: "Cassius Wren",
  },
  {
    id: "CC-2026-0408",
    slug: "private-commission-c4",
    title: "Private Commission · Collector C4",
    productionHouse: "Concierge Desk",
    productionType: "Private Commission",
    location: "Soho, NY (closed set)",
    shootWindow: "May 9, 2026 — single day",
    ratePerDayCents: 1200000,
    ratePerDayLabel: "$12,000 / day",
    closesOn: "2026-05-04",
    postedOn: "2026-04-29",
    status: "Final Callbacks",
    union: "Non-Union",
    exclusivity: "Single-collector, view-once delivery",
    usage: "View-once playback to single recipient",
    brief:
      "Long-standing collector requests a private editorial film. Closed set, six-person crew, no on-set photography. Final delivery via view-once access policy with forensic watermark binding.",
    requirements: [
      "Tier 4 verification",
      "NDA + revocable consent",
      "References from previous private commissions",
    ],
    submissionsCount: 38,
    spots: 1,
    posterUrl:
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1600&q=80",
    director: "Mara Soto",
  },
  {
    id: "CC-2026-0405",
    slug: "ourial-cinema-feature",
    title: "Ourial Cinema · Feature Lead",
    productionHouse: "Ourial Films",
    productionType: "Film",
    location: "Brooklyn & Hudson Valley",
    shootWindow: "Jun 1 — Jul 18, 2026",
    ratePerDayCents: 220000,
    ratePerDayLabel: "$2,200 / day · weekly",
    closesOn: "2026-05-12",
    postedOn: "2026-04-21",
    status: "Open",
    union: "SAG-AFTRA",
    exclusivity: "Theatrical + streaming, North America",
    usage: "Feature theatrical + festival circuit",
    brief:
      "Lead role in a chamber drama directed by an A24 alumna. Six-week shoot. Strong dialog and three intimate scenes coordinated by certified intimacy director.",
    requirements: [
      "Self-tape with two scripted scenes",
      "Available full shoot window",
      "Intimacy coordination cooperation",
    ],
    submissionsCount: 894,
    spots: 1,
    posterUrl:
      "https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1600&q=80",
    director: "Sasha Quinn",
  },
  {
    id: "CC-2026-0399",
    slug: "loretta-fragrance",
    title: "Loretta Atelier · Fragrance Film",
    productionHouse: "Loretta Atelier",
    productionType: "Commercial",
    location: "Manhattan rooftops",
    shootWindow: "May 14 — May 16, 2026",
    ratePerDayCents: 600000,
    ratePerDayLabel: "$6,000 / day",
    closesOn: "2026-05-06",
    postedOn: "2026-04-23",
    status: "Closing Soon",
    union: "Either",
    exclusivity: "Worldwide fragrance category, 24 months",
    usage: "Global digital + OOH",
    brief:
      "60-second fragrance film, 15s and 6s cutdowns. Looking for a face that holds the camera in silence. Reading not required.",
    requirements: [
      "Tier 3 verification",
      "Single-frame stillness reel",
      "Open availability for talent test",
    ],
    submissionsCount: 612,
    spots: 2,
    posterUrl:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1600&q=80",
    director: "Idris Mahmoud",
    photographer: "Lena Halberg",
  },
  {
    id: "CC-2026-0395",
    slug: "stage-31-runway",
    title: "Stage 31 · Resort Runway",
    productionHouse: "Stage 31",
    productionType: "Runway",
    location: "Cipriani 25 Broadway",
    shootWindow: "May 24, 2026 (single show)",
    ratePerDayCents: 300000,
    ratePerDayLabel: "$3,000 / show + fittings",
    closesOn: "2026-05-15",
    postedOn: "2026-04-25",
    status: "Open",
    union: "Non-Union",
    exclusivity: "Show + B-roll usage",
    usage: "Runway + brand archive",
    brief:
      "Resort show featuring 14 looks. Two openers, one closer, eleven turn looks. Movement and presence weighted heavier than runway resume.",
    requirements: [
      "Two fittings between May 18-22",
      "Show day full availability",
    ],
    submissionsCount: 528,
    spots: 14,
    posterUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80",
    director: "Petra Vance",
  },
  {
    id: "CC-2026-0392",
    slug: "private-magazine-22",
    title: "Private Magazine · Issue 22 Cover",
    productionHouse: "Private Magazine",
    productionType: "Editorial",
    location: "Industrial loft, Long Island City",
    shootWindow: "May 10 — May 11, 2026",
    ratePerDayCents: 180000,
    ratePerDayLabel: "$1,800 / day",
    closesOn: "2026-05-03",
    postedOn: "2026-04-26",
    status: "Closing Soon",
    union: "Non-Union",
    exclusivity: "Print + digital editorial, 12 months",
    usage: "Cover + 18-page editorial",
    brief:
      "Independent biannual returning to print. Cover plus interior story shot on medium format film. Photographer is a long-time collaborator of the publication.",
    requirements: ["Tier 2+ verification", "Comfort on long film day"],
    submissionsCount: 240,
    spots: 3,
    posterUrl:
      "https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=1600&q=80",
    director: "Niko Bauer",
    photographer: "Cassius Wren",
  },
];

export const bookings: Booking[] = [
  {
    id: "BK-2026-0511",
    contentId: "01HZ9X8M0001",
    title: "Maison Vermeer · Studio Day 1",
    client: "Maison Vermeer",
    status: "Confirmed",
    callTime: "May 18, 2026 — 06:30",
    location: "Pier 59 Studios, NY",
    rateCents: 850000,
    rateLabel: "$8,500",
  },
  {
    id: "BK-2026-0509",
    contentId: "01HZ9X8M0002",
    title: "Loretta Atelier · Talent Test",
    client: "Loretta Atelier",
    status: "Confirmed",
    callTime: "May 6, 2026 — 14:00",
    location: "501 W 24th, NY",
    rateCents: 120000,
    rateLabel: "$1,200",
  },
  {
    id: "BK-2026-0501",
    contentId: "01HZ9X8M0003",
    title: "Private Commission · Collector C4",
    client: "Concierge Desk",
    status: "On Hold",
    callTime: "May 9, 2026 — TBD",
    location: "SoHo, NY (private)",
    rateCents: 1200000,
    rateLabel: "$12,000",
  },
  {
    id: "BK-2026-0494",
    contentId: "01HZ9X8M0004",
    title: "Stage 31 · Resort Runway",
    client: "Stage 31",
    status: "Pending",
    callTime: "May 24, 2026 — 11:00",
    location: "Cipriani 25 Broadway",
    rateCents: 300000,
    rateLabel: "$3,000",
  },
];

export const uploads: UploadItem[] = [
  {
    id: "UP-01HZ9001",
    title: "Latex Editorial — Studio 8",
    duration: "07:24",
    uploadedOn: "Apr 28, 2026",
    state: "playable",
    views: 14820,
    earningsCents: 612400,
    earningsLabel: "$6,124.00",
    posterUrl:
      "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=80",
    accessTier: "subscriber",
  },
  {
    id: "UP-01HZ9002",
    title: "Movement Reel · Spring Atelier",
    duration: "03:11",
    uploadedOn: "Apr 21, 2026",
    state: "playable",
    views: 6240,
    earningsCents: 184200,
    earningsLabel: "$1,842.00",
    posterUrl:
      "https://images.unsplash.com/photo-1508807526345-15e9b5f4eaff?auto=format&fit=crop&w=1200&q=80",
    accessTier: "open",
  },
  {
    id: "UP-01HZ9003",
    title: "Private Commission · C4 (delivered)",
    duration: "12:48",
    uploadedOn: "Apr 14, 2026",
    state: "playable",
    views: 1,
    earningsCents: 1200000,
    earningsLabel: "$12,000.00",
    posterUrl:
      "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=80",
    accessTier: "view-once",
  },
  {
    id: "UP-01HZ9004",
    title: "Boudoir Series · 04",
    duration: "09:02",
    uploadedOn: "May 2, 2026",
    state: "pipeline_running",
    views: 0,
    earningsCents: 0,
    earningsLabel: "$0.00",
    posterUrl:
      "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=1200&q=80",
    accessTier: "ppv",
  },
  {
    id: "UP-01HZ9005",
    title: "Behind the Cipriani Show",
    duration: "04:36",
    uploadedOn: "May 1, 2026",
    state: "pending_2257_review",
    views: 0,
    earningsCents: 0,
    earningsLabel: "$0.00",
    posterUrl:
      "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1200&q=80",
    accessTier: "subscriber",
  },
];

export const press: PressMention[] = [
  {
    outlet: "The New York Times — Style",
    headline: "A Casting House for the Post-Agency Era",
    date: "Apr 2026",
    url: "#",
  },
  {
    outlet: "i-D",
    headline: "How Casting / NY Built a Private Studio for a Loud Internet",
    date: "Mar 2026",
    url: "#",
  },
  {
    outlet: "WWD",
    headline: "Inside the Manhattan Platform Quietly Booking the City",
    date: "Feb 2026",
    url: "#",
  },
  {
    outlet: "The Cut",
    headline: "The First Casting Platform That Models Actually Trust",
    date: "Jan 2026",
    url: "#",
  },
];

export const tickerLines = [
  "INVITATION-LED",
  "MANHATTAN-BRED",
  "PRIVATE BY DEFAULT",
  "EST. 2026",
  "NON-INDEXABLE",
  "REPRESENTED, NEVER OWNED",
  "NEW YORK / PARIS / TOKYO",
];

export function findCreator(handle: string): Creator | undefined {
  return creators.find((c) => c.handle === handle);
}

export function findCastingCall(slug: string): CastingCall | undefined {
  return castingCalls.find((c) => c.slug === slug);
}
